server:
  port: 8060

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:https://service-registry-f8b1.onrender.com/eureka/}

management:
  tracing:
    sampling:
      probability: 1.0
      
spring:
  data:
    redis:
      host: redis-14434.c292.ap-southeast-1-1.ec2.redns.redis-cloud.com
      port: 14434
      password: QSXXcWgl2sserlbefUsJlestoMv5fuF9
  cloud:
    gateway:
      httpclient:
        ssl:
          use-insecure-trust-manager: true
      routes:
        - id: auth-service
          uri: https://auth-service-yl52.onrender.com
          predicates:
            - Path=/auth/**
            - Path=/oauth2/**
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/friends/**
            - Path=/user/**
      globalcors:
        corsConfigurations:
          '[/**]':
            # allowedOrigins: "https://localhost:3000"
            allowedOriginPatterns: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - PATCH
            allowedHeaders:
              - "*"
            allowCredentials: true
  main:
    web-application-type: reactive

jwt:
  secret: 04ca023b39512e46d0c2cf4b48d5aac61d34302994c87ed4eff225dcf3b0a218739f3897051a057f9b846a69ea2927a587044164b7bae5e1306219d50b588cb1