server:
  port: 9004

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}

management:
  tracing:
    sampling:
      probability: 1.0

spring:
  data:
    redis:
      host: redis-14434.c292.ap-southeast-1-1.ec2.redns.redis-cloud.com
      port: 14434
      password: QSXXcWgl2sserlbefUsJlestoMv5fuF9
  datasource:
    url: jdbc:mysql://uzwn5xabb6g4leoj:ztk0GbYx1HKJYFR5xyLw@bucjeknhu545oao2934p-mysql.services.clever-cloud.com:3306/bucjeknhu545oao2934p
    username: uzwn5xabb6g4leoj
    password: ztk0GbYx1HKJYFR5xyLw
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 32927445083-prq50j015hn7k7k7tmjpljmttfaftn43.apps.googleusercontent.com
            clientSecret: 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
            redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - email
              - profile
          facebook:
            clientId: 348437084584351
            clientSecret: 8a82539290d778626ad541250ce04bb3
            redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - public_profile
              - email
        provider:
          facebook:
            authorizationUri: https://www.facebook.com/v20.0/dialog/oauth
            tokenUri: https://graph.facebook.com/v20.0/oauth/access_token
            userInfoUri: https://graph.facebook.com/v20.0/me?fields=id,first_name,middle_name,last_name,name,email,verified,picture.width(250).height(250)
app:
  auth:
    tokenSecret: 04ca023b39512e46d0c2cf4b48d5aac61d34302994c87ed4eff225dcf3b0a218739f3897051a057f9b846a69ea2927a587044164b7bae5e1306219d50b588cb1
    tokenExpirationMsec: 864000000
  cors:
    allowedOrigins: http://localhost:3000,http://localhost:8080
  oauth2:
    authorizedRedirectUris:
      - http://localhost:3000/oauth2/redirect