server:
  port: 8086

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true

spring:
  data:
    mongodb:
      uri: mongodb+srv://mongobasic:Social123456789Media@cluster0.oiyfqvw.mongodb.net/chat_db?retryWrites=true&w=majority&appName=Cluster0
  rabbitmq:
    host: octopus.rmq3.cloudamqp.com
    port: 5671
    username: jripffqi
    password: FU4X3xuxkVca33eee0zB3UomHrvN6_x_
    virtual-host: jripffqi
    ssl:
      enabled: true
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration