server:
  port: 8087

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true

spring:
  data:
    redis:
      database: 0
      host: redis-14434.c292.ap-southeast-1-1.ec2.redns.redis-cloud.com
      port: 14434
      password: QSXXcWgl2sserlbefUsJlestoMv5fuF9
  rabbitmq:
    host: octopus.rmq3.cloudamqp.com
    port: 5671
    username: jripffqi
    password: FU4X3xuxkVca33eee0zB3UomHrvN6_x_
    virtual-host: jripffqi
    ssl:
      enabled: true
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

jwt:
  secret: 04ca023b39512e46d0c2cf4b48d5aac61d34302994c87ed4eff225dcf3b0a218739f3897051a057f9b846a69ea2927a587044164b7bae5e1306219d50b588cb1