server:
  port: 8088

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true

spring:
  data:
    mongodb:
      uri: mongodb+srv://mongobasic:Social123456789Media@cluster0.oiyfqvw.mongodb.net/post_db?retryWrites=true&w=majority&appName=Cluster0
    elasticsearch:
      cluster-name: elasticsearch
      cluster-nodes: localhost:9200
  neo4j:
    uri: neo4j+s://d227dd4a.databases.neo4j.io
    authentication:
      username: neo4j
      password: 27q2I0_Lhc144m96JvGCFxPe6dDq5qCjfqWXlRwcYZ0
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration