server:
  port: 8082

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:https://service-registry-f8b1.onrender.com/eureka/}

management:
  tracing:
    sampling:
      probability: 1.0

spring:
  neo4j:
    uri: neo4j+s://d227dd4a.databases.neo4j.io
    authentication:
      username: neo4j
      password: 27q2I0_Lhc144m96JvGCFxPe6dDq5qCjfqWXlRwcYZ0
  rabbitmq:
    host: octopus.rmq3.cloudamqp.com
    port: 5671
    username: jripffqi
    password: FU4X3xuxkVca33eee0zB3UomHrvN6_x_
    virtual-host: jripffqi
    ssl:
      enabled: true